analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#67ADB1'
    - '#602C2B'
    - '#F38D99'
    - '#FFD200'
  brandStrength: 0.668918
  lightness: 0.324556
  rhythmicContrast: 0.444819
  saturation: 0.878378
cta: {}
layout_spectrum: 0.408783
name: Storybook Nanny
opengraph: {}
purpose: []
typography_spectrum: 0.5414760154671967
